package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Txemistry/Documents/workspace/Proyecto ISO/RehearsalReservationCore/idl/corbaServer.idl
* domingo 28 de marzo de 2010 18H49' CEST
*/

public interface ICorbaServer extends ICorbaServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaServer
