package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Tutto/RehearsalReservationCore/idl/corbaServer.idl
* lunes 29 de marzo de 2010 17H56' CEST
*/

public interface ICorbaServerOperations 
{
  corbaServer.corba.corbaServerRehearsalDTO[] getRehearsals ();
} // interface ICorbaServerOperations
