package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/tutto/RehearsalReservationCore/idl/corbaServer.idl
* martes 11 de mayo de 2010 13H50' CEST
*/

public interface ICorbaServerOperations 
{
  corbaServer.corba.corbaServerRehearsalDTO[] getRehearsals ();
} // interface ICorbaServerOperations
