module corbaServer
{
    module corba
    {

   		// Data transfer object to be transmitted
        struct corbaServerRehearsalDTO
        {
           string operaName;
	       string date;	
	       long seats;
        };
        
        interface ICorbaServer
        {
        	typedef sequence <corbaServerRehearsalDTO> rehearsalsList;
        	rehearsalsList getRehearsals();
        };
        
                  	
  //  The rest of the IDL file must be completed by the students     
	};
};