package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Txemistry/Documents/workspace/Proyecto ISO/RehearsalReservationCore/idl/corbaServer.idl
* jueves 25 de marzo de 2010 17H42' CET
*/

public interface ICorbaServerOperations 
{
  corbaServer.corba.corbaServerRehearsalDTO[] getRehearsals ();
} // interface ICorbaServerOperations
