package corbaServer.corba;

/**
* corbaServer/corba/ICorbaServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Txemistry/Documents/workspace/Proyecto ISO/RehearsalReservationCore/idl/corbaServer.idl
* domingo 28 de marzo de 2010 18H49' CEST
*/

public final class ICorbaServerHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaServer.corba.ICorbaServer value = null;

  public ICorbaServerHolder ()
  {
  }

  public ICorbaServerHolder (corbaServer.corba.ICorbaServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaServer.corba.ICorbaServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaServer.corba.ICorbaServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaServer.corba.ICorbaServerHelper.type ();
  }

}
