package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/corbaServer.idl
* miércoles 10 de marzo de 2010 15H30' CET
*/

public interface ICorbaServerOperations 
{
  corbaServer.corba.corbaServerRehearsalDTO[] getRehearsals ();
} // interface ICorbaServerOperations
