package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/tutto/RehearsalReservationCore/idl/corbaServer.idl
* jueves 29 de abril de 2010 12H05' CEST
*/

public interface ICorbaServer extends ICorbaServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaServer
